### ISSUE TITLE
Readme typo?

### ISSUE THREAD

**Issue by paulshapiro** [tblobaum/dnode-session#4]
Hey man,

Thanks for this awesome lib. Been using it for a while. Just upgraded to the latest version and had to change some code, but found that the docs may be wrong:

```
this.cookies(callback)

    Return the cookies that would be available from req.cookies in express

cookies(function(cookies) {
     // ...
})
```

I was only able to find "cookie" in 'this'...

Or maybe it is a quirk of my individual setup?
- Paul

**Comment by tblobaum** [comment]
Hmm. I didnt catch this right away, but I will look into this.  Any chance you could post a bit more code? Can `cookies` be used?

**Comment by paulshapiro** [comment]
Hi there,

It seems in my version that 'cookies' could not be used.

I don't think I have much extra code, it seems to be that I just have to call "this.cookie()" instead of "this.cookies()", but here's the general (and very stripped down) structure of my dnode auth code, along with versions, in case it helps

```
var dnode_app = function (client, conn) {

    var dnode_self = this;

    dnode_self.subscribe = function (emit) {

        // ...

        sessionCheck(dnode_self, client, conn, function(sid) {
            if ( sid ) {
                subs[sid] = emit;
            }
        })

    };
}



function sessionCheck(dnode_self, client, conn, callback) {
    dnode_self.session(function(err, sess) {

        // ...

        dnode_self.cookie(function(cookie) {
            var sid = cookie ? unescape(cookie["connect.sid"]) : null;

            // ...

        })
    });
}


// ...

var dnode_server = dnode();
dnode_server.use(app_modules.dnode_session({ 
                                            store: app_modules.sessionStore,
                                            secret: app_modules.session_secret, 
                                            keepAlive: true, 
                                            interval: 120000
                                            }));
dnode_server.use(dnode_app);
dnode_server.listen(app_modules.app);
```

Versions:

Node 0.6.6
DNode 0.9.2
Socket.IO 0.8.7
DNode session 0.3.0

Thanks!

**Comment by tblobaum** [comment]
@paulshapiro try running `npm install dnode-session@0.3.1` and the readme should match up, cookie is renamed to cookies
